# BULKI_Store Demo

## Starting Server

In [1]:
print("Let's start")

Let's start


In [2]:
# import subprocess

# # Start the server as a background process
# server_process = subprocess.Popen(
#     ['/opt/homebrew/bin/mpirun', '-np', '4', 'target/debug/bulkistore-server'],
#     env={'RUST_LOG': 'debug'},
#     stdout=subprocess.PIPE,
#     stderr=subprocess.PIPE
# )

# print("Server started with PID:", server_process.pid)


## Creating Arrays

In [17]:
import bkstore_client as bkc
import numpy as np
import time
from pprint import pprint


bkc.init()
dim_size = 30
# dim_size = 10
rd1 = np.random.rand(dim_size, dim_size, dim_size, dim_size, dim_size)
rd2 = np.random.rand(dim_size, dim_size, dim_size, dim_size, dim_size)

print("rd1.shape=", rd1.shape)
print("rd1 last 2 dim preview:")
print(rd1[0:1, 0:1, 0:1, 0:2, 0:])

print("rd2.shape=", rd2.shape)
print("rd2 last 2 dim preview:")
print(rd2[0:1, 0:1, 0:1, 0:2, 0:])

arr3 = np.random.rand(dim_size, dim_size, dim_size)
print("arr3.shape=", arr3.shape)
print("arr3 last 2 dim preview:")
print(arr3[0:1, 0:2, 0:])

rd1.shape= (30, 30, 30, 30, 30)
rd1 last 2 dim preview:
[[[[[0.83530762 0.28517054 0.23464052 0.06011267 0.0836561  0.05412838
     0.69555836 0.16703058 0.9697215  0.31844473 0.72000673 0.03619856
     0.04592782 0.22960481 0.64440281 0.71984227 0.80622524 0.16722018
     0.12185155 0.82521495 0.83402022 0.97691937 0.85999834 0.59195939
     0.34105782 0.01571436 0.08103747 0.21027425 0.20317027 0.00781364]
    [0.18251348 0.45735532 0.02218776 0.88591631 0.08681742 0.19982163
     0.35914562 0.61793808 0.03013961 0.47364205 0.21993181 0.1694567
     0.49694851 0.1875646  0.641487   0.41077009 0.46888275 0.17514652
     0.9691049  0.47537427 0.95080991 0.82295741 0.37539532 0.56620715
     0.55042728 0.27133577 0.48690315 0.44867598 0.6475609  0.33409953]]]]]
rd2.shape= (30, 30, 30, 30, 30)
rd2 last 2 dim preview:
[[[[[0.84464395 0.33898458 0.43946686 0.12040771 0.41672283 0.3002843
     0.20235488 0.7934037  0.91813889 0.44943142 0.85942041 0.92522227
     0.33880773 0.19672126 0.155

## Client-Side NDArray Arithmetic Operation

In [4]:
arr4 = bkc.polymorphic_add(rd1, rd2)

print("arr4.shape=", arr4.shape)
print("arr4 last 2 dim preview:")
print(arr4[0:1, 0:1, 0:1, 0:2, 0:])



arr4.shape= (30, 30, 30, 30, 30)
arr4 last 2 dim preview:
[[[[[1.09492056 1.20159122 1.32304836 1.01106636 1.04825856 0.4148741
     0.17874274 0.76266214 0.88180429 0.68628156 0.82604549 1.00376194
     1.27159142 0.22229415 1.44118707 0.59806031 1.64214536 1.80123525
     1.58314885 1.12110157 0.7333863  0.579052   0.48458843 1.16630068
     0.94718892 0.04161488 1.28540736 0.44534985 1.61985934 1.27275795]
    [1.3132254  1.13735371 1.42087435 0.77321598 0.68810399 0.74854899
     1.32760406 1.10101427 1.54294453 0.81768619 1.18200428 1.15514494
     1.86438769 1.21553468 0.76245323 0.66014381 1.08310199 0.68496096
     0.86835896 0.38612682 1.34512293 0.37782284 1.46907158 0.98186061
     0.50412889 1.36099875 1.91018734 1.05592587 1.42160073 1.46950945]]]]]


## Remote Array Slicing

In [5]:
arr5 = bkc.array_slicing(arr4, [slice(0, 1), slice(0, 1), slice(0, 1), slice(0, 2), slice(0, 10, -2)])

print("arr5.shape=", arr4.shape)
print("arr5 last 2 dim preview:")
print(arr5[0:1, 0:1, 0:1, 0:2, 0:])



arr5.shape= (30, 30, 30, 30, 30)
arr5 last 2 dim preview:
[[[[[0.68628156 0.76266214 0.4148741  1.01106636 1.20159122]
    [0.81768619 1.10101427 0.74854899 0.77321598 1.13735371]]]]]


## Remote Array Arithmetic Operation

In [6]:
arr6 = bkc.times_two(arr5)

print("arr6.shape=", arr6.shape)
print("arr6:")
print(arr6)

arr6.shape= (1, 1, 1, 2, 5)
arr6:
[[[[[1.37256312 1.52532428 0.8297482  2.02213271 2.40318245]
    [1.63537237 2.20202853 1.49709797 1.54643197 2.27470742]]]]]


## Creating Object with Multiple NDArrays

1. You can attach a series of metadata attributes directly to the object you are creating
2. You can attach a series of NDArrays directly to the object you are creating along with the metadata attributes of these NDArrays.
3. Each of these NDArrays will become a sub-object of the main object you are creating.

In [7]:
# Create an 3D array

name_id=str(np.random.rand(1)[0]*1000000)[0:6]

obj_ids = bkc.create_objects(
    obj_name_key="name",
    parent_id=None,
    metadata={
        "name": "{}".format(name_id),
        "type": "container",
        "keys": [
            "{}/arr6".format(name_id), 
            "{}/arr5".format(name_id), 
            "{}/arr4".format(name_id)
                ],
        "ranges": [(1, 100), (100, 200)],
        "part_num": 1,
        "part_size": 100,
    },
    data=arr3,
    array_meta_list=[
        {
            "name": "{}/arr6".format(name_id),
            "type": "array",
            "shape": arr6.shape,
            "vcount": 100,
            "voffset": 0,
            "vdim": 0,
        },
        {
            "name": "{}/arr5".format(name_id),
            "type": "array",
            "shape": arr6.shape,
            "vcount": 100,
            "voffset": 0,
            "vdim": 0,
        },
        {
            "name": "{}/arr4".format(name_id),
            "type": "array",
            "shape": arr4.shape,
            "vcount": 100,
            "voffset": 0,
            "vdim": 0,
        },
        {
            "name": "{}/arr3".format(name_id),
            "type": "array",
            "shape": arr3.shape,
            "vcount": 100,
            "voffset": 0,
            "vdim": 0,
        }
    ],
    array_data_list=[arr6, arr5, arr4, arr3],
)
print(obj_ids)

[32110535053899391886048204973740419, 32110535053900111309067083941220739, 32110535053900369563484120169910659, 32110535053900535584180787850842499, 32110535054221656505015928020341123]


## Retrieve Metadata

### Retrieve a single metadata attributes from a single object


In HydraGNN, we need to retrieve a series of metadata attributes from a container. 

If every single metadata retrieval requires a single request, that would be too much overhead.

MetaPS is a new metric we designed to calculate the number of metadata attributes we can retrieve from one object within a second.


In [8]:
meta_keys=["type", "keys", "ranges", "name", "part_num", "part_size"]

start = time.time()
for i in range(1000):
    k = i % len(meta_keys)
    result = bkc.get_object_metadata(
        obj_ids[0],
        meta_keys=[meta_keys[k]], # retreiving SINGLE!!!
        
    )
    if i < len(meta_keys):
        print(result)

print("Single Metadata retrieval of single object : TPS = {} MetaPS: {}".format(1000/(time.time()-start), 1000/(time.time()-start)))

{'obj_id': 32110535053899391886048204973740419, 'metadata': {'type': 'container'}, 'sub_obj_metadata': None}
{'obj_id': 32110535053899391886048204973740419, 'metadata': {'keys': ['558457/arr6', '558457/arr5', '558457/arr4']}, 'sub_obj_metadata': None}
{'obj_id': 32110535053899391886048204973740419, 'metadata': {'ranges': [(1, 100), (100, 200)]}, 'sub_obj_metadata': None}
{'obj_id': 32110535053899391886048204973740419, 'metadata': {'name': '558457'}, 'sub_obj_metadata': None}
{'obj_id': 32110535053899391886048204973740419, 'metadata': {'part_num': 1}, 'sub_obj_metadata': None}
{'obj_id': 32110535053899391886048204973740419, 'metadata': {'part_size': 100}, 'sub_obj_metadata': None}
Single Metadata retrieval of single object : TPS = 1420.8236182441667 MetaPS: 1420.8216930265205


### Retrieving multiple metadata attributes from a single object

Now we can combine the metadata retrieval of a single container into one single request. 

MetaPS is a new metric we designed to calculate the number of metadata attributes we can retrieve from one object within a second.

Slight drop on TPS but MEGA IMPROVEMENT for MetaPS

In [9]:
meta_keys=["type", "keys", "ranges", "name", "part_num", "part_size"]

start = time.time()
for i in range(1000):
    result = bkc.get_object_metadata(
        obj_ids[0],
        meta_keys=meta_keys, # retrieving MULTIPLE!!!
    )
pprint(result)
print("\n Multiple Metadata retrieval of single object : TPS={}, MetaPS: {} ".format(1000/(time.time()-start), 1000*len(meta_keys)/(time.time()-start) ))

{'metadata': {'keys': ['558457/arr6', '558457/arr5', '558457/arr4'],
              'name': '558457',
              'part_num': 1,
              'part_size': 100,
              'ranges': [(1, 100), (100, 200)],
              'type': 'container'},
 'obj_id': 32110535053899391886048204973740419,
 'sub_obj_metadata': None}

 Multiple Metadata retrieval of single object : TPS=1343.0591863841473, MetaPS: 8058.344796846061 


### Retrieving single attributes from a single sub-object

In [10]:
meta_keys=["name",
            "type",
            "shape",
            "vcount",
            "voffset",
            "vdim"]

start = time.time()
for i in range(1000):
    k = i % len(meta_keys)
    result = bkc.get_object_metadata(
        obj_ids[1],
        meta_keys=[meta_keys[k]], # retreiving SINGLE!!!
        
    )
    if i < len(meta_keys):
        print(result)

print("Single Metadata retrieval of a single sub-object : TPS={}, MetaPS: {}".format(1000/(time.time()-start), 1000/(time.time()-start)))

{'obj_id': 32110535053900111309067083941220739, 'metadata': {'name': '558457/arr6'}, 'sub_obj_metadata': None}
{'obj_id': 32110535053900111309067083941220739, 'metadata': {'type': 'array'}, 'sub_obj_metadata': None}
{'obj_id': 32110535053900111309067083941220739, 'metadata': {'shape': [1, 1, 1, 2, 5]}, 'sub_obj_metadata': None}
{'obj_id': 32110535053900111309067083941220739, 'metadata': {'vcount': 100}, 'sub_obj_metadata': None}
{'obj_id': 32110535053900111309067083941220739, 'metadata': {'voffset': 0}, 'sub_obj_metadata': None}
{'obj_id': 32110535053900111309067083941220739, 'metadata': {'vdim': 0}, 'sub_obj_metadata': None}
Single Metadata retrieval of a single sub-object : TPS=1500.0041127317659, MetaPS: 1500.001966955857


### Retrieving multiple attributes from single sub-objects

In [11]:
meta_keys=["name",
            "type",
            "shape",
            "vcount",
            "voffset",
            "vdim"]

start = time.time()
for i in range(1000):
    result = bkc.get_object_metadata(
        obj_ids[1],
        meta_keys=meta_keys, # retreiving SINGLE!!!
        
    )
    
pprint(result)
print("\n Multiple Metadata retrieval of a single sub-object : TPS={}, MetaPS: {}".format(1000/(time.time()-start), 1000*len(meta_keys)/(time.time()-start)))

{'metadata': {'name': '558457/arr6',
              'shape': [1, 1, 1, 2, 5],
              'type': 'array',
              'vcount': 100,
              'vdim': 0,
              'voffset': 0},
 'obj_id': 32110535053900111309067083941220739,
 'sub_obj_metadata': None}

 Multiple Metadata retrieval of a single sub-object : TPS=1388.2140104131672, MetaPS: 8329.27303532072


### Retrieving multiple attributes from multiple sub-objects

In [12]:
meta_keys=["name",
            "type",
            "shape",
            "vcount",
            "voffset",
            "vdim"]

start = time.time()
for i in range(1000):
    result = bkc.get_object_metadata(
        obj_ids[0],
        sub_meta_keys=meta_keys, # retreiving MULTIPLE for every sub-object!!!     
    )

pprint(result)
print("Multiple Metadata retrieval of a single sub-object : TPS={}, MetaPS: {}".format(1000/(time.time()-start), 1000*len(meta_keys)*3/(time.time()-start)))

{'metadata': {},
 'obj_id': 32110535053899391886048204973740419,
 'sub_obj_metadata': [{'metadata': {'name': '558457/arr3',
                                    'shape': [30, 30, 30],
                                    'type': 'array',
                                    'vcount': 100,
                                    'vdim': 0,
                                    'voffset': 0},
                       'name': '558457/arr3',
                       'obj_id': 32110535054221656505015928020341123},
                      {'metadata': {'name': '558457/arr6',
                                    'shape': [1, 1, 1, 2, 5],
                                    'type': 'array',
                                    'vcount': 100,
                                    'vdim': 0,
                                    'voffset': 0},
                       'name': '558457/arr6',
                       'obj_id': 32110535053900111309067083941220739},
                      {'metadata': {'name': '558457/arr5',

### Retrieving different set of attributes from multiple sub-objects

In [13]:
# meta_keys=["name",
#             "type",
#             "shape",
#             "vcount",
#             "voffset",
#             "vdim"]

start = time.time()
for i in range(1000):
    result = bkc.get_object_metadata(
        obj_ids[0],
        sub_meta_keys={"{}/arr5".format(name_id):[ "name", "type", "voffset" ],
                      "{}/arr4".format(name_id):["type", "vcount"]}      # retrieving different set of metadata for different sub-objects
    )

pprint(result)
print("\n Multiple Metadata retrieval of a single sub-object : TPS={}, MetaPS: {}".format(1000/(time.time()-start), 1000*5/(time.time()-start)))

{'metadata': {},
 'obj_id': 32110535053899391886048204973740419,
 'sub_obj_metadata': [{'metadata': {'type': 'array', 'vcount': 100},
                       'name': '558457/arr4',
                       'obj_id': 32110535053900535584180787850842499},
                      {'metadata': {'name': '558457/arr5',
                                    'type': 'array',
                                    'voffset': 0},
                       'name': '558457/arr5',
                       'obj_id': 32110535053900369563484120169910659}]}

 Multiple Metadata retrieval of a single sub-object : TPS=1287.5082381969314, MetaPS: 6437.535262673536


### Retrieving array of a single object

In [14]:
start = time.time()
for i in range(1000):
    result = bkc.get_object_data(
        obj_ids[0],
        region=[slice(0, 1), slice(0, 1), slice(0, 2, -1)],
        
    )
pprint(result)
print("\n retrieving array slice of a single 3D array, TPS={}".format(1000/(time.time()-start)))

{'array_slice': array([[[0.19111042, 0.52209557]]]), 'sub_obj_slices': []}

 retrieving array slice of a single 3D array, TPS=1294.9859210591314


### Retrieving array slices of multiple sub-objects

In [15]:
start = time.time()
for i in range(1000):
    result = bkc.get_object_data(
        obj_ids[0],
        region=[slice(0, 1), slice(0, 2), slice(0, 2, -1)],
        sub_obj_regions=[
            (
                "{}/arr5".format(name_id),
                [slice(0, 1), slice(0, 1), slice(0, 1), slice(0, 2), slice(0, 2, -1)],
            ),
            (
                "{}/arr4".format(name_id),
                [slice(0, 1), slice(0, 1), slice(0, 1), slice(0, 2), slice(0, 2, -1)],
            ),
            (
                "{}/arr3".format(name_id),
                [slice(0, 1), slice(0, 2), slice(0, 10, -2)],
            ),
            (
                "{}/arr6".format(name_id),
                [slice(0, 1), slice(0, 1), slice(0, 1), slice(0, 2), slice(0, 2, -1)],
            ),
        ]
    )
pprint(result)
print("\n retrieving array slice of a single 3D array, TPS={}".format(1000/(time.time()-start)))

{'array_slice': array([[[0.19111042, 0.52209557],
        [0.2580603 , 0.46225924]]]),
 'sub_obj_slices': [{'array': array([[[[[0.76266214, 0.68628156],
          [1.10101427, 0.81768619]]]]]),
                     'id': 32110535053900369563484120169910659,
                     'name': '558457/arr5'},
                    {'array': array([[[[[1.20159122, 1.09492056],
          [1.13735371, 1.3132254 ]]]]]),
                     'id': 32110535053900535584180787850842499,
                     'name': '558457/arr4'},
                    {'array': array([[[0.70486965, 0.19935725, 0.49362348, 0.39882897, 0.19111042],
        [0.26340503, 0.51764171, 0.49076661, 0.81150914, 0.2580603 ]]]),
                     'id': 32110535054221656505015928020341123,
                     'name': '558457/arr3'},
                    {'array': array([[[[[1.52532428, 1.37256312],
          [2.20202853, 1.63537237]]]]]),
                     'id': 32110535053900111309067083941220739,
                     'name':

## Closing the Store

In [16]:
# server_process.terminate()
# server_process.wait()
# print("Server process terminated.")
