# BULKI_Store Demo

## Starting Server

In [1]:
print("Let's start")

Let's start


In [2]:
# import subprocess

# # Start the server as a background process
# server_process = subprocess.Popen(
#     ['/opt/homebrew/bin/mpirun', '-np', '4', 'target/debug/bulkistore-server'],
#     env={'RUST_LOG': 'debug'},
#     stdout=subprocess.PIPE,
#     stderr=subprocess.PIPE
# )

# print("Server started with PID:", server_process.pid)


## Creating Arrays

In [3]:
import bkstore_client as bkc
import numpy as np
import time
from pprint import pprint


bkc.init()
dim_size = 30
# dim_size = 10
rd1 = np.random.rand(dim_size, dim_size, dim_size, dim_size, dim_size)
rd2 = np.random.rand(dim_size, dim_size, dim_size, dim_size, dim_size)

print("rd1.shape=", rd1.shape)
print("rd1 last 2 dim preview:")
print(rd1[0:1, 0:1, 0:1, 0:2, 0:])

print("rd2.shape=", rd2.shape)
print("rd2 last 2 dim preview:")
print(rd2[0:1, 0:1, 0:1, 0:2, 0:])

arr3 = np.random.rand(dim_size, dim_size, dim_size)
print("arr3.shape=", arr3.shape)
print("arr3 last 2 dim preview:")
print(arr3[0:1, 0:2, 0:])

rd1.shape= (30, 30, 30, 30, 30)
rd1 last 2 dim preview:
[[[[[0.46824756 0.52435137 0.34284734 0.94868289 0.47485708 0.11313337
     0.10332374 0.74568728 0.28901149 0.39103599 0.59401542 0.80641589
     0.61866746 0.21317878 0.81903027 0.50948797 0.7221415  0.88455528
     0.77714449 0.39918413 0.00893057 0.06479203 0.44213083 0.73410953
     0.6823386  0.03578243 0.29209011 0.22092523 0.66835361 0.4355572 ]
    [0.68441225 0.49587977 0.92341621 0.68927688 0.60352158 0.21796419
     0.4185946  0.24847672 0.95302988 0.04425627 0.33884361 0.91004243
     0.89477258 0.35254452 0.33712353 0.44108776 0.44644471 0.08624796
     0.46648422 0.31380644 0.79781535 0.16779194 0.62488392 0.37728856
     0.10954606 0.88164574 0.93091213 0.16819754 0.50845877 0.54687877]]]]]
rd2.shape= (30, 30, 30, 30, 30)
rd2 last 2 dim preview:
[[[[[0.626673   0.67723986 0.98020102 0.06238347 0.57340148 0.30174072
     0.075419   0.01697487 0.5927928  0.29524557 0.23203008 0.19734605
     0.65292396 0.00911536 0.6

## Client-Side NDArray Arithmetic Operation

In [4]:
arr4 = bkc.polymorphic_add(rd1, rd2)

print("arr4.shape=", arr4.shape)
print("arr4 last 2 dim preview:")
print(arr4[0:1, 0:1, 0:1, 0:2, 0:])



arr4.shape= (30, 30, 30, 30, 30)
arr4 last 2 dim preview:
[[[[[1.09492056 1.20159122 1.32304836 1.01106636 1.04825856 0.4148741
     0.17874274 0.76266214 0.88180429 0.68628156 0.82604549 1.00376194
     1.27159142 0.22229415 1.44118707 0.59806031 1.64214536 1.80123525
     1.58314885 1.12110157 0.7333863  0.579052   0.48458843 1.16630068
     0.94718892 0.04161488 1.28540736 0.44534985 1.61985934 1.27275795]
    [1.3132254  1.13735371 1.42087435 0.77321598 0.68810399 0.74854899
     1.32760406 1.10101427 1.54294453 0.81768619 1.18200428 1.15514494
     1.86438769 1.21553468 0.76245323 0.66014381 1.08310199 0.68496096
     0.86835896 0.38612682 1.34512293 0.37782284 1.46907158 0.98186061
     0.50412889 1.36099875 1.91018734 1.05592587 1.42160073 1.46950945]]]]]


## Remote Array Slicing

In [5]:
arr5 = bkc.array_slicing(arr4, [slice(0, 1), slice(0, 1), slice(0, 1), slice(0, 2), slice(0, 10, -2)])

print("arr5.shape=", arr4.shape)
print("arr5 last 2 dim preview:")
print(arr5[0:1, 0:1, 0:1, 0:2, 0:])



arr5.shape= (30, 30, 30, 30, 30)
arr5 last 2 dim preview:
[[[[[0.68628156 0.76266214 0.4148741  1.01106636 1.20159122]
    [0.81768619 1.10101427 0.74854899 0.77321598 1.13735371]]]]]


## Remote Array Arithmetic Operation

In [6]:
arr6 = bkc.times_two(arr5)

print("arr6.shape=", arr6.shape)
print("arr6:")
print(arr6)

arr6.shape= (1, 1, 1, 2, 5)
arr6:
[[[[[1.37256312 1.52532428 0.8297482  2.02213271 2.40318245]
    [1.63537237 2.20202853 1.49709797 1.54643197 2.27470742]]]]]


## Creating Object with Multiple NDArrays

1. You can attach a series of metadata attributes directly to the object you are creating
2. You can attach a series of NDArrays directly to the object you are creating along with the metadata attributes of these NDArrays.
3. Each of these NDArrays will become a sub-object of the main object you are creating.

In [ ]:
# Create an 3D array

name_id=str(np.random.rand(1)[0]*1000000)[0:6]

obj_ids = bkc.create_objects(
    obj_name_key="name",
    parent_id=None,
    metadata={
        "name": "{}".format(name_id),
        "type": "container",
        "keys": [
            "{}/arr6".format(name_id), 
            "{}/arr5".format(name_id), 
            "{}/arr4".format(name_id)
                ],
        "ranges": [(1, 100), (100, 200)],
        "part_num": 1,
        "part_size": 100,
    },
    data=arr3,
    array_meta_list=[
        {
            "name": "{}/arr6".format(name_id),
            "type": "array",
            "shape": arr6.shape,
            "vcount": 100,
            "voffset": 0,
            "vdim": 0,
        },
        {
            "name": "{}/arr5".format(name_id),
            "type": "array",
            "shape": arr6.shape,
            "vcount": 100,
            "voffset": 0,
            "vdim": 0,
        },
        {
            "name": "{}/arr4".format(name_id),
            "type": "array",
            "shape": arr4.shape,
            "vcount": 100,
            "voffset": 0,
            "vdim": 0,
        },
        {
            "name": "{}/arr3".format(name_id),
            "type": "array",
            "shape": arr3.shape,
            "vcount": 100,
            "voffset": 0,
            "vdim": 0,
        }
    ],
    array_data_list=[arr6, arr5, arr4, arr3],
)
print(obj_ids)

## Retrieve Metadata

### Retrieve a single metadata attributes from a single object


In HydraGNN, we need to retrieve a series of metadata attributes from a container. 

If every single metadata retrieval requires a single request, that would be too much overhead.

MetaPS is a new metric we designed to calculate the number of metadata attributes we can retrieve from one object within a second.


In [ ]:
meta_keys=["type", "keys", "ranges", "name", "part_num", "part_size"]

start = time.time()
for i in range(1000):
    k = i % len(meta_keys)
    result = bkc.get_object_metadata(
        obj_ids[0],
        meta_keys=[meta_keys[k]], # retreiving SINGLE!!!
        
    )
    if i < len(meta_keys):
        print(result)

print("Single Metadata retrieval of single object : TPS = {} MetaPS: {}".format(1000/(time.time()-start), 1000/(time.time()-start)))

### Retrieving multiple metadata attributes from a single object

Now we can combine the metadata retrieval of a single container into one single request. 

MetaPS is a new metric we designed to calculate the number of metadata attributes we can retrieve from one object within a second.

Slight drop on TPS but MEGA IMPROVEMENT for MetaPS

In [ ]:
meta_keys=["type", "keys", "ranges", "name", "part_num", "part_size"]

start = time.time()
for i in range(1000):
    result = bkc.get_object_metadata(
        obj_ids[0],
        meta_keys=meta_keys, # retrieving MULTIPLE!!!
    )
pprint(result)
print("\n Multiple Metadata retrieval of single object : TPS={}, MetaPS: {} ".format(1000/(time.time()-start), 1000*len(meta_keys)/(time.time()-start) ))

### Retrieving single attributes from a single sub-object

In [ ]:
meta_keys=["name",
            "type",
            "shape",
            "vcount",
            "voffset",
            "vdim"]

start = time.time()
for i in range(1000):
    k = i % len(meta_keys)
    result = bkc.get_object_metadata(
        obj_ids[1],
        meta_keys=[meta_keys[k]], # retreiving SINGLE!!!
        
    )
    if i < len(meta_keys):
        print(result)

print("Single Metadata retrieval of a single sub-object : TPS={}, MetaPS: {}".format(1000/(time.time()-start), 1000/(time.time()-start)))

### Retrieving multiple attributes from single sub-objects

In [ ]:
meta_keys=["name",
            "type",
            "shape",
            "vcount",
            "voffset",
            "vdim"]

start = time.time()
for i in range(1000):
    result = bkc.get_object_metadata(
        obj_ids[1],
        meta_keys=meta_keys, # retreiving SINGLE!!!
        
    )
    
pprint(result)
print("\n Multiple Metadata retrieval of a single sub-object : TPS={}, MetaPS: {}".format(1000/(time.time()-start), 1000*len(meta_keys)/(time.time()-start)))

### Retrieving multiple attributes from multiple sub-objects

In [ ]:
meta_keys=["name",
            "type",
            "shape",
            "vcount",
            "voffset",
            "vdim"]

start = time.time()
for i in range(1000):
    result = bkc.get_object_metadata(
        obj_ids[0],
        sub_meta_keys=meta_keys, # retreiving MULTIPLE for every sub-object!!!     
    )

pprint(result)
print("Multiple Metadata retrieval of a single sub-object : TPS={}, MetaPS: {}".format(1000/(time.time()-start), 1000*len(meta_keys)*3/(time.time()-start)))

### Retrieving different set of attributes from multiple sub-objects

In [ ]:
# meta_keys=["name",
#             "type",
#             "shape",
#             "vcount",
#             "voffset",
#             "vdim"]

start = time.time()
for i in range(1000):
    result = bkc.get_object_metadata(
        obj_ids[0],
        sub_meta_keys={"{}/arr5".format(name_id):[ "name", "type", "voffset" ],
                      "{}/arr4".format(name_id):["type", "vcount"]}      # retrieving different set of metadata for different sub-objects
    )

pprint(result)
print("\n Multiple Metadata retrieval of a single sub-object : TPS={}, MetaPS: {}".format(1000/(time.time()-start), 1000*5/(time.time()-start)))

### Retrieving array of a single object

In [ ]:
start = time.time()
for i in range(1000):
    result = bkc.get_object_data(
        obj_ids[0],
        region=[slice(0, 1), slice(0, 1), slice(0, 2, -1)],
        
    )
pprint(result)
print("\n retrieving array slice of a single 3D array, TPS={}".format(1000/(time.time()-start)))

### Retrieving array slices of multiple sub-objects

In [ ]:
start = time.time()
for i in range(1000):
    result = bkc.get_object_data(
        obj_ids[0],
        region=[slice(0, 1), slice(0, 2), slice(0, 2, -1)],
        sub_obj_regions=[
            (
                "{}/arr5".format(name_id),
                [slice(0, 1), slice(0, 1), slice(0, 1), slice(0, 2), slice(0, 2, -1)],
            ),
            (
                "{}/arr4".format(name_id),
                [slice(0, 1), slice(0, 1), slice(0, 1), slice(0, 2), slice(0, 2, -1)],
            ),
            (
                "{}/arr3".format(name_id),
                [slice(0, 1), slice(0, 2), slice(0, 10, -2)],
            ),
            (
                "{}/arr6".format(name_id),
                [slice(0, 1), slice(0, 1), slice(0, 1), slice(0, 2), slice(0, 2, -1)],
            ),
        ]
    )
pprint(result)
print("\n retrieving array slice of a single 3D array, TPS={}".format(1000/(time.time()-start)))

## Closing the Store

In [ ]:
# server_process.terminate()
# server_process.wait()
# print("Server process terminated.")
